{% set version = "0.3.6" %}

package:
  name: usgs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/usgs/usgs-{{ version }}.tar.gz
  sha256: 417d772ed3b9e4ecbe3524d0d1d3cde14dcf3a4e3833feb9d319ce7f66adca11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - usgs = usgs.scripts.cli:usgs

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - click >=4.0
    - requests >=2.7.0
    - requests-futures >=0.9.5

test:
  imports:
    - usgs
    - usgs.scripts
  commands:
    - pip check
    - usgs --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kapadia/usgs
  license: ISC
  license_file: LICENSE
  summary: Access the USGS inventory service

extra:
  recipe-maintainers:
    - ocefpaf
