{% set version = "0.3.5" %}

package:
  name: usgs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/usgs/usgs-{{ version }}.tar.gz
  sha256: 62734bfd23829e8b90701c49cb2f868d3bf4c706ea6b53939711186cf6df0807

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - usgs = usgs.scripts.cli:usgs

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - click >=4.0
    - requests >=2.7.0
    - requests-futures >=0.9.5

test:
  imports:
    - usgs
    - usgs.scripts
  commands:
    - pip check
    - usgs --help
  requires:
    - pip

about:
  home: https://github.com/kapadia/usgs
  license: ISC
  license_file: LICENSE
  summary: Access the USGS inventory service

extra:
  recipe-maintainers:
    - ocefpaf
